
pipeline {
    agent any
    stages {
        stage {
            steps {
                sh "./mvnw verify"
                // how to expose template parameters such as "$recipient"
                mail body: 'build successful', subject: "$repoName", to: "$recipient"

            }
        }
    }
}